project:
  type: website

website:
  page-navigation: true
  title: "STA 210 - Spring 2022"
  description: "Homepage for STA 210 - Regression Analysis at Duke University, Spring 2022."
  site-url: "https://sta210-s22.github.io/website/"

  repo-url: https://github.com/sta210-s22/website
  repo-actions: [edit, issue]

  opengraph: true
  twitter-card:
    creator: "@minebocek"
    image: "images/twitter-card.png"

  page-footer: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sta210-s22
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: person-fill
        text: "Sakai"
        menu:
          - text: Discussion forum
            url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/13b6446a-a6c6-4222-8cfb-c36d1f70802b
          - text: Gradescope
            url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/page/aec742dc-2972-4f02-a35b-1dd3315af889
          - text: Gradebook
            url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/69078433-67a6-4054-a2e7-9e6c202ecdc3/

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
      - section: "Labs"
        contents:
          - href: labs/lab-0.qmd
            text: "Lab 0"
          - href: labs/lab-1.qmd
            text: "Lab 1"
          - href: labs/lab-2.qmd
            text: "Lab 2"
          - href: labs/lab-3.qmd
            text: "Lab 3"
          - href: labs/lab-4.qmd
            text: "Lab 4"
          - href: labs/lab-5.qmd
            text: "Lab 5"
          - href: labs/lab-6.qmd
            text: "Lab 6"
          - href: labs/lab-7.qmd
            text: "Lab 7"
      - section: "HW"
        contents:
          - href: hw/hw-1.qmd
            text: "HW 1"
          - href: hw/hw-2.qmd
            text: "HW 2"
          - href: hw/hw-3.qmd
            text: "HW 3"
          - href: hw/hw-4.qmd
            text: "HW 4"
          - href: hw/hw-5.qmd
            text: "HW 5"
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
