project:
  type: website

website:

  title: "STA 210 - Spring 2022"

  sidebar:

    tools:
      - icon: github
        href: https://github.com/sta210-s22
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
      - icon: person-fill
        menu:
          - text: Discussion forum
            url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/13b6446a-a6c6-4222-8cfb-c36d1f70802b
          - text: Gradescope
            url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/page/aec742dc-2972-4f02-a35b-1dd3315af889
          - text: Gradebook
            url: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/69078433-67a6-4054-a2e7-9e6c202ecdc3/

    style: "docked"
    search: true
    contents:
      - section: "Course information"
        contents:
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Teaching team
          - href: course-schedule.qmd
            text: Schedule
          - href: course-support.qmd
            text: Support
          - href: course-links.qmd
            text: Useful links
      - section: "Computing"
        contents:
          - computing-access.qmd
          - computing-troubleshooting.qmd
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources

format:
  html:
    theme:
      light: cosmo
      dark: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
