project:
  type: website

website:

  title: "STA 210 - Spring 2022"

  navbar:
    logo: "images/logo.png"
    type: dark
    background: "#44757A"
    right:
      - href: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/
        text: Sakai
      - href: https://github.com/sta210-s22
        icon: github
      - href: https://cmgr.oit.duke.edu/containers
        icon: code-square
      - href: https://sakai.duke.edu/portal/site/779c3ebe-3b88-4bcc-bd01-1813e8396a23/tool/13b6446a-a6c6-4222-8cfb-c36d1f70802b
        icon: chat

  sidebar:
    style: "floating"
    contents:
      - section: "Course information"
        contents:
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-team.qmd
            text: Teaching team
          - href: course-schedule.qmd
            text: Schedule
          - href: course-support.qmd
            text: Support
          - course-links.qmd
      - section: "Computing"
        contents:
          - computing-access.qmd
          - computing-troubleshooting.qmd
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
